version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    versioning-strategy: increase
    labels:
      - "type:dependencies"
    assignees:
      - "thujcak"
    reviewers:
      - "thujcak"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    versioning-strategy: increase
    labels:
      - "type:dependencies"
    assignees:
      - "thujcak"
    reviewers:
      - "thujcak"

  - package-ecosystem: npm
    directory: "/apps/typing-test"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    versioning-strategy: increase
    labels:
      - "type:dependencies"
    assignees:
      - "thujcak"
    reviewers:
      - "thujcak"

  - package-ecosystem: npm
    directory: "/apps/web-calc"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    versioning-strategy: increase
    labels:
      - "type:dependencies"
    assignees:
      - "thujcak"
    reviewers:
      - "thujcak"

  - package-ecosystem: npm
    directory: "/apps/web-calc-featured"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    versioning-strategy: increase
    labels:
      - "type:dependencies"
    assignees:
      - "thujcak"
    reviewers:
      - "thujcak"

  - package-ecosystem: npm
    directory: "/lib/widgets/qu-checklists"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    versioning-strategy: increase
    labels:
      - "type:dependencies"
    assignees:
      - "thujcak"
    reviewers:
      - "thujcak"

  - package-ecosystem: npm
    directory: "/lib/widgets/qu-expertnote"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    versioning-strategy: increase
    labels:
      - "type:dependencies"
    assignees:
      - "thujcak"
    reviewers:
      - "thujcak"

  - package-ecosystem: npm
    directory: "/lib/widgets/qu-howtos"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    versioning-strategy: increase
    labels:
      - "type:dependencies"
    assignees:
      - "thujcak"
    reviewers:
      - "thujcak"

  - package-ecosystem: npm
    directory: "/lib/widgets/statistics"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    versioning-strategy: increase
    labels:
      - "type:dependencies"
    assignees:
      - "thujcak"
    reviewers:
      - "thujcak"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
    labels:
      - "type:dependencies"
    assignees:
      - "thujcak"
    reviewers:
      - "thujcak"
